typedef signed char int_8;
typedef unsigned char uint_8;
typedef signed char* int_8_ptr;
typedef unsigned char* uint_8_ptr;
typedef signed short int_16;
typedef unsigned short uint_16;
typedef signed short* int_16_ptr;
typedef unsigned short* uint_16_ptr;
typedef signed int int_32;
typedef unsigned int uint_32;
typedef signed int* int_32_ptr;
typedef unsigned int* uint_32_ptr;
typedef signed long long int_64;
typedef unsigned long long uint_64;
typedef signed long long* int_64_ptr;
typedef unsigned long long* uint_64_ptr;
typedef float float_32;
typedef float* float_32_ptr;
typedef double float_64;
typedef double* float_64_ptr;
